import type { SimpleTranslationKey } from "./dictionaries/en";

/**
 * English question -> display keys.
 *
 * The English question string stays the IDENTITY: it is what
 * PREVIEW_QUESTIONS in FaqPreview looks entries up by, and what the accordion
 * uses as its item value. Translating it in place would break both — the
 * preview would find nothing and the accordion would lose its open/closed
 * state on a language change.
 *
 * Generated by scripts alongside the dictionary; if a question is reworded in
 * data/faqs.ts, update the key here in the same commit.
 */
export const FAQ_LABELS: Record<
  string,
  { question: SimpleTranslationKey; answer: SimpleTranslationKey }
> = {
  "What's included in a program?": { question: "faqItem.q1", answer: "faqItem.a1" },
  "Is this a subscription? Will I be billed again?": {
    question: "faqItem.q2",
    answer: "faqItem.a2",
  },
  "What happens in the first consultation?": { question: "faqItem.q3", answer: "faqItem.a3" },
  "Do you offer online consultations?": { question: "faqItem.q4", answer: "faqItem.a4" },
  "How do consultation credits work?": { question: "faqItem.q5", answer: "faqItem.a5" },
  "What happens if I don't use all my credits?": { question: "faqItem.q6", answer: "faqItem.a6" },
  "How do I join my online consultation?": { question: "faqItem.q7", answer: "faqItem.a7" },
  "How do I create an account?": { question: "faqItem.q8", answer: "faqItem.a8" },
  "Is my payment information secure?": { question: "faqItem.q9", answer: "faqItem.a9" },
  "Can I purchase products directly on the site?": {
    question: "faqItem.q10",
    answer: "faqItem.a10",
  },
  "How soon will I see results?": { question: "faqItem.q11", answer: "faqItem.a11" },
  "Is the plan built around foods I already eat?": {
    question: "faqItem.q12",
    answer: "faqItem.a12",
  },
  "Can you work with an existing medical condition?": {
    question: "faqItem.q13",
    answer: "faqItem.a13",
  },
  "Do you provide guidance for seniors?": { question: "faqItem.q14", answer: "faqItem.a14" },
  "Do you support patients going through cancer treatment?": {
    question: "faqItem.q15",
    answer: "faqItem.a15",
  },
  "How do I book a session?": { question: "faqItem.q16", answer: "faqItem.a16" },
  "What is your cancellation policy?": { question: "faqItem.q17", answer: "faqItem.a17" },
};
